site_name: Wingram.Org
site_url: https://wingram.org
site_description: "Wingram on the way we find the Truth"
site_author: Wingram.Org
copyright: "Don't forget bookmark this site. You can forget this site, but you can't forget an Ideology"
# repo_url: https://github.com/codegram01/WingramOrg
# edit_uri: blob/main/docs/

docs_dir: src
site_dir: docs
extra_css:
  - assets/css/style.css
extra_javascript:
  - assets/js/main.js
theme:
  name: mkdocs
  locale: en
  custom_dir: theme/
  color_mode: auto
  user_color_mode_toggle: true

nav:
  - Home: README.md

watch:
  - src
  - theme
  - mkdocs.yml
#strict: true

plugins:
  - search:
      indexing: 'full'
# markdown_extensions:
#   - toc:
#       permalink: "#"